config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  
  devise_for :users

  resources :products
  resources :carts, only: [:show]
  resource :cart_items, except: [:show]
  resources :orders
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy

  def grand_total
    cart_items.map(&:total_price).sum
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  validates :shipping_address, :payment_method, presence: true

  belongs_to :user
  has_many :order_items, dependent: :destroy
  after_create :create_order_items

  private

  def create_order_items
    cart_items = user.cart.cart_items
    cart_items.each do |cart_item|
      order_item = order_items.new
      order_item.product_id = cart_item.product_id
      order_item.quantity = cart_item.quantity

      if order_item.save
        cart_item.delete
      else
        raise ActiveRecord::Rollback
      end
    end
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, :description, :price, :quantity, :category, :brand, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :cart
  has_many :orders, dependent: :destroy

  after_create :create_cart
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  helper_method :current_cart

  private

  def current_cart
    @current_cart ||= current_user&.cart
  end
end

app/controllers/cart_items_controller.rb
# app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :set_cart_item, only: [:show, :edit, :update, :destroy]

  def create
    @cart_item = current_cart.cart_items.find_or_initialize_by(product_id: params[:product_id])
    @cart_item.quantity += 1
    @cart_item.total_price = @cart_item.product.price * @cart_item.quantity

    if @cart_item.save
      render json: {items_count: current_cart.cart_items.count}, status: 200
    else
      render json: {error: @cart_item.errors}, status: 400
    end
  end

  def update
    if @cart_item.update(cart_item_params)
      redirect_to current_cart, notice: 'Cart item quantity updated.'
    else
      redirect_to current_cart, alert: 'Error updating cart item quantity.'
    end
  end

  def destroy
    @cart_item.destroy
    redirect_to current_cart, notice: 'Cart item removed.'
  end

  private

  def set_cart_item
    @cart_item = CartItem.find(params[:id])
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show;end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    @order.user = current_user
    @order.total_amount = current_cart.grand_total
    @order.status = 'order_placed'

    if @order.save
      redirect_to products_path, notice: "Order Successfully created!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def order_params
    params.require(:order).permit(:shipping_address, :payment_method)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :price, :quantity, :category, :brand)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/carts/show.html.erb
<% current_cart.cart_items.each do |cart_item| %>
  <div class="card w-75 my-3">
    <div class="card-body">
      <div class="row">
        <div class="col-md-4">
          <img src="https://images.unsplash.com/photo-1505740420928-5e560c06d30e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80" style="width:80%; height:200px;">
        </div>
        <div class="col-md-8">
          <h5 class="card-title"><%= cart_item.product.name %></h5>
          <p class="card-text"><%= cart_item.product.description %></p>
          <p class="card-text">Price: <strong><%= cart_item.product.price %>₹</strong></p>
          <p class="card-text">Total Quantity: <strong><%= cart_item.quantity %></strong></p>
          <p class="card-text">Total Price: <strong><%= cart_item.quantity * cart_item.product.price %>₹</strong></p>
        </div>
      </div>
    </div>
  </div>
<% end %>

<div class="d-grid gap-2 col-6 mx-auto">
  <% if current_cart.cart_items.any? %>
    <%= link_to "Checkout", new_order_path, class: "btn btn-success my-4" %>.
  <% else %>
    <h2>Cart is empty</h2>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/"><strong>Shopping Cart</strong></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class:"nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "Products", products_path, class:"nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to current_cart, class:"nav-link active" do%>
            <i class="bi bi-cart item-count"></i>
          <% end %>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShoppingCart</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "layouts/navbar" %>

    <p class="navbar-text float-right">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to "Edit profile", edit_user_registration_path, class: "navbar-link" %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "navbar-link"  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, class: "navbar-link"  %> |
      <%= link_to "Login", new_user_session_path, class: "navbar-link"  %>
    <% end %>
    </p>

    <% if notice%>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <p class="alert"><%= alert %></p>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/orders/new.html.erb
<main class="page payment-page">
  <section class="payment-form dark">
    <div class="container">
      <div class="block-heading">
        <h2>Payment</h2>
      </div>
        <div class="products">
          <h3 class="title">Checkout</h3>
          <% current_cart.cart_items.each do |cart_item| %>
            <div class="item">
              <span class="price"><%= "#{cart_item.product.price} x #{cart_item.quantity}" %></span>
              <p class="item-name"><%= cart_item.product.name %></p>
              <p class="item-description"><%= cart_item.product.description %></p>
            </div>
          <% end %>
          <div class="total">Total<span class="price"><%= current_cart.grand_total %></span></div>
        </div>
    </div>
  </section>
  <%= form_for @order do |f| %>
    <% if @order.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@order.errors.count, "error") %> prohibited this product from being saved:</h2>

        <ul>
          <% @order.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-group my-3">
        <%= f.label :shipping_address, 'Shipping Address' %>
        <%= f.text_area :shipping_address, class:'form-control mt-3', row: 3 %>
    </div>
    <div class="form-group my-3">
      <%= f.label :payment_method %>
      <%= f.select :payment_method, ['Case on delivery'], class: 'form-control' %>
    </div>
    <%= f.submit 'Place Order', class: "btn btn-primary" %>
  <% end %>
</main>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :quantity, style: "display: block" %>
    <%= form.number_field :quantity %>
  </div>

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.text_field :category %>
  </div>

  <div>
    <%= form.label :brand, style: "display: block" %>
    <%= form.text_field :brand %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= product.description %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= product.quantity %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= product.category %>
  </p>

  <p>
    <strong>Brand:</strong>
    <%= product.brand %>
  </p>

</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<h1>Products</h1>

<%= link_to "New product", new_product_path %>

<div id="products">
  <div class="row">
    <% @products.each do |product| %>
      <div class="col-md-4 my-3">
        <div class="card">
          <%= link_to product do %>
            <img src="https://images.unsplash.com/photo-1505740420928-5e560c06d30e?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80" style="width:100%; height:300px;">
          <% end %>
          <div class="card-body">
            <%= link_to product do %>
              <h5 class="card-title"><%= product.name %></h5>
            <% end %>
            <p class="card-text"><%= product.description %></p>
            <h3 class="card-text"><%= product.price %>₹</h3>
            <%= link_to "#", method: :post, class: 'btn btn-primary add-to-cart', data: { product_id: product.id } do %>
              <i class="bi bi-cart"></i> Add to cart
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>

app/views/welcome/index.html.erb
<h1>Welcome! to on shopping cart</h1>